name: "01-Master Student Card"
description: "A central issue for managing student's information."
labels: [master-card, student-profile]
projects: ["CHI-CityTech/34"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ### 🎓 **Master Student Card**
        This issue serves as the central tracking card for a student's research activities.

  - type: input
    id: student_name
    attributes:
      label: "🆔 Student Name (GitHub Handle Preferred)"
      description: "Insert full name"
      placeholder: "E.g., Jane Doe"
    validations:
      required: true

  - type: input
    id: student_major
    attributes:
      label: "🆔 Academic Major"
      description: "Your major or department here"
      placeholder: "E.g., Computer Systems Technology"
    validations:
      required: true

  - type: input
    id: github_username
    attributes:
      label: "🐙 GitHub Username"
      description: "Use your GitHub handle (@username) to create a direct profile link."
      placeholder: "E.g., @janedoe"
    validations:
      required: true

  - type: input
    id: zotero_username
    attributes:
      label: "📚 Zotero Username"
      description: "Enter your Zotero username here."
      placeholder: "E.g., janedoe"
    validations:
      required: true

  - type: input
    id: discord_username
    attributes:
      label: "💬 Discord Username"
      description: "Enter your Discord username here."
      placeholder: "E.g., janedoe"
    validations:
      required: true

  - type: input
    id: project_repo
    attributes:
      label: "📂 Project Repository"
      description: "Provide the GitHub repository link for your project."
      placeholder: "E.g., https://github.com/YOUR_ORG/YOUR_PROJECT"
    validations:
      required: true

  - type: input
    id: project_board
    attributes:
      label: "📌 GitHub Project Board"
      description: "Provide the link to your GitHub Project Board for tracking tasks."
      placeholder: "E.g., https://github.com/orgs/YOUR_ORG/projects/XX"
    validations:
      required: true

  - type: textarea
    id: research_focus
    attributes:
      label: "🔍 Research Focus"
      description: "Describe the key research area you are working on."
      placeholder: "E.g., Blended Reality Performance Systems and AI collaboration"
    validations:
      required: true

  - type: textarea
    id: weekly_checkins
    attributes:
      label: "📆 Weekly Check-ins"
      description: "This section will be automatically updated as new Weekly Check-ins are submitted."
      value: "No check-ins yet."

  - type: textarea
    id: notes
    attributes:
      label: "📝 Additional Notes"
      description: "Any extra details, challenges, or feedback regarding this research."
 
  - type: checkboxes
    id: final_check
    attributes:
      label: "✅ Final Confirmation"
      options:
        - label: "I confirm this card will be used for my research tracking."
          required: true
