  - type: input
    id: project_board
    attributes:
      label: "📌 GitHub Project Board"
      description: "Provide the link to your GitHub Project Board for tracking tasks."
      placeholder: "E.g., https://github.com/orgs/YOUR_ORG/projects/XX"
