name: "Master Student Card 2"
description: "A central issue for tracking an individual student's research progress."
labels: [master-card, student-profile]
projects: ["CHI-CityTech/34"]  # ✅ Ensures this issue is added to the CHI Meta-Project Board
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ### 🎓 **Master Student Card**
        This issue serves as the central tracking card for a student's research activities.

  - type: input
    id: student_name
    attributes:
      label: "🆔 Student Name"
      description: "Enter your full name."
      placeholder: "E.g., Jane Doe"

  - type: dropdown
    id: effort_type
    attributes:
      label: "📌 Type of Effort"
      description: "Select the type of academic or research effort."
      options:
        - "Culmination"
        - "Independent Study"
        - "Internship"
        - "Research Project"
        - "Capstone"
        - "Other"
    validations:
      required: true

  - type: input
    id: project_repo
    attributes:
      label: "📂 Project Repository"
      description: "Provide the GitHub repository link for your project."
      placeholder: "E.g., https://github.com/YOUR_ORG/YOUR_PROJECT"

  - type: input
    id: project_board
    attributes:
      label: "📌 GitHub Project Board"
      description: "Provide the link to your **own project board** (if applicable)."
      placeholder: "E.g., https://github.com/orgs/YOUR_ORG/projects/XX"

  - type: textarea
    id: research_focus
    attributes:
      label: "🔍 Research Focus"
      description: "Describe your research focus or project goal."
      placeholder: "E.g., Blended Reality Performance Systems and AI collaboration"

  - type: textarea
    id: weekly_checkins
    attributes:
      label: "📆 Weekly Check-ins"
      description: "This section will be automatically updated as new Weekly Check-ins are submitted."
      value: "No check-ins yet."

  - type: textarea
    id: milestones
    attributes:
      label: "🚀 Milestones"
      description: "List major milestones and progress tracking points."
      placeholder: "- Proposal Submitted\n- Prototype Development\n- Final Presentation"

  - type: textarea
    id: notes
    attributes:
      label: "📝 Additional Notes"
      description: "Any extra details, challenges, or feedback regarding this research."
